### ISSUE TITLE
ModuleNotFoundError: No module named 'networkx

### ISSUE THREAD

**Issue by sogun1998** [amitsk1994/mininetShortestPath#1]
I get error : 
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.32', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python3.6/dist-packages/ryu/cmd/manager.py", line 98, in main
    app_mgr.load_apps(app_lists)
  File "/usr/local/lib/python3.6/dist-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/local/lib/python3.6/dist-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/usr/local/lib/python3.6/dist-packages/ryu/utils.py", line 99, in import_module
    return _import_module_file(modname)
  File "/usr/local/lib/python3.6/dist-packages/ryu/utils.py", line 88, in _import_module_file
    return load_source(modname, abspath)
  File "/usr/local/lib/python3.6/dist-packages/ryu/utils.py", line 42, in load_source
    return loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/environment/test.py", line 13, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
Plese help me :100:

**Comment by jmoeyersons** [comment]
`$ pip install networkx` ;-)
